# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160729_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kituser',
            name='sms_balance',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
