# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160729_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kituser',
            name='sms_balance',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
