# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160814_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='kituser',
            name='free_sms_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
