# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160729_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kituser',
            name='sms_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
