# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_uploadedcontact_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='kituser',
            name='email_validated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kituser',
            name='email_validated_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 21, 21, 58, 845657, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kituser',
            name='phone_validated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kituser',
            name='phone_validated_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 21, 22, 15, 658463, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kituser',
            name='state',
            field=models.CharField(choices=[('OYO', 'Oyo'), ('ABIA', 'Abia'), ('LAG', 'Lagos'), ('ABJ', 'Abuja'), ('ONDO', 'Ondo'), ('KANO', 'Kano'), ('OTHER', 'Other')], default='LAG', max_length=100),
        ),
    ]
