# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 15:42
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import phonenumber_field.modelfields
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_kitactivationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitactivationcode',
            name='email_activation_code',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=28, max_length=28, unique=True),
        ),
        migrations.AlterField(
            model_name='kitactivationcode',
            name='phone_activation_code',
            field=models.CharField(db_index=True, default=core.models.get_random_integers, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='kituser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
