# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160830_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitactivationcode',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
