# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160830_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='kituser',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.1'),
            preserve_default=False,
        ),
    ]
