# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160830_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kituser',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
