# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160830_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kituser',
            name='ip_address',
            field=models.GenericIPAddressField(editable=False, null=True),
        ),
    ]
