# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160903_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kituser',
            old_name='company',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='kituser',
            name='industry',
            field=models.CharField(choices=[('AVIATION', 'Aviation'), ('ENTERTAINMENT', 'Entertainment'), ('RELIGIOUS', 'Religious'), ('FIN_BANK', 'Finance & Banking'), ('EDUCATION', 'Education'), ('MARKETING', 'Marketing'), ('GOVERNMENT', 'Government'), ('OIL_ENERGY', 'Oil & Energy'), ('NGO', 'NGO'), ('IT', 'Information Technology'), ('RETAIL', 'Retail'), ('TRANSPORT_HAULAGE', 'Transportation & Haulage'), ('TRAVEL_TOURISM', 'Travel & Tourism'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
