# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_smtpsetting_cou_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactgroup',
            options={'verbose_name': 'Contact List'},
        ),
    ]
