# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160908_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsetting',
            name='cou_group',
            field=models.ManyToManyField(blank=True, to='core.CoUserGroup', verbose_name='Group Availability'),
        ),
    ]
