# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20160914_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='insert_optout',
            field=models.BooleanField(default=1, verbose_name='Insert Unsubscribe'),
            preserve_default=False,
        ),
    ]
