# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_messagetemplate_insert_optout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='smtp_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SMTPSetting', verbose_name='SMTP Account'),
        ),
    ]
