# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20160926_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='industry',
            field=models.CharField(choices=[('AVIATION', 'Aviation'), ('ENTERTAINMENT', 'Entertainment'), ('RELIGIOUS', 'Religious'), ('FIN_BANK', 'Finance & Banking'), ('EDUCATION', 'Education'), ('MARKETING', 'Marketing'), ('GOVERNMENT', 'Government'), ('OIL_ENERGY', 'Oil & Energy'), ('NGO', 'NGO'), ('IT', 'Information Technology'), ('RETAIL', 'Retail'), ('TRANSPORT_HAULAGE', 'Transportation & Haulage'), ('TRAVEL_TOURISM', 'Travel & Tourism'), ('INSURANCE', 'Insurance'), ('LEGAL', 'Legal Services'), ('GOVERNMENT', 'Government'), ('HOSPITALITY', 'Hotel & Recreation'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
