# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20160927_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
