# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20161002_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicevent',
            name='recipients',
        ),
        migrations.AddField(
            model_name='publicevent',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, to='core.ContactGroup'),
        ),
    ]
