# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_smtpsetting_cloud_smtp_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='last_run',
            new_name='next_run',
        ),
    ]
