# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20161108_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitubalance',
            name='free_sms_balance',
        ),
        migrations.RemoveField(
            model_name='kitubalance',
            name='sms_balance',
        ),
        migrations.AddField(
            model_name='kitubalance',
            name='user_balance',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=12),
            preserve_default=False,
        ),
    ]
