# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20161108_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smstransfer',
            name='sms_units',
        ),
        migrations.AddField(
            model_name='smstransfer',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=10.04, max_digits=12),
            preserve_default=False,
        ),
    ]
