# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20161108_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitubalance',
            name='user_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
