# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20161127_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='email_reply_to',
            field=models.CharField(blank=True, max_length=500, verbose_name='Reply To'),
        ),
    ]
