# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_messagetemplate_email_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='email_reply_to',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='email_reply_to',
            field=models.ManyToManyField(null=True, to='core.Contact', verbose_name='Reply To'),
        ),
    ]
