# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0043_auto_20161108_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
        migrations.CreateModel(
            name='CallStatus',
            fields=[
                ('job_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
    ]
