# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 21:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import messaging.models
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedMessaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField(default=messaging.models.get_default_time, verbose_name='Deliver at')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('waiting', 'waiting'), ('processed', 'processed')], default='draft', max_length=100, no_check_for_status=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact_group', models.ManyToManyField(to='core.ContactGroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MessageTemplate')),
            ],
            options={
                'verbose_name_plural': 'Advanced Messaging',
            },
        ),
        migrations.CreateModel(
            name='EmailReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[(0, 'Sent'), (1, 'Delivered'), (2, 'Deferred'), (3, 'Bounce')], default=0, max_length=100, no_check_for_status=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('email_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('email_gateway', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('ADVANCED', ' Advanced'), ('STANDARD', ' Standard')], max_length=10)),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
            options={
                'verbose_name_plural': 'Processed Messages',
            },
        ),
        migrations.CreateModel(
            name='QueuedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('ADVANCED', ' Advanced'), ('STANDARD', ' Standard')], max_length=10)),
                ('message_id', models.PositiveIntegerField()),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('delivery_time', models.DateTimeField(default=messaging.models.get_default_time, verbose_name='Deliver at')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
            options={
                'verbose_name_plural': 'Queued Messages',
            },
        ),
        migrations.CreateModel(
            name='SMSReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('sms_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sms_gateway', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', model_utils.fields.StatusField(choices=[(0, 'Delivered'), (1, 'Accepted'), (2, 'Expired'), (3, 'Undelivered'), (4, 'Rejected')], default=0, max_length=100, no_check_for_status=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
        ),
        migrations.CreateModel(
            name='StandardMessaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email_message', models.TextField(blank=True)),
                ('sms_message', models.TextField(blank=True)),
                ('send_sms', models.BooleanField(verbose_name='Send SMS')),
                ('send_email', models.BooleanField(verbose_name='Send Email')),
                ('delivery_time', models.DateTimeField(default=messaging.models.get_default_time, verbose_name='Deliver at')),
                ('sms_sender', models.CharField(blank=True, max_length=11)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('waiting', 'waiting'), ('processed', 'processed')], default='draft', max_length=100, no_check_for_status=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
                ('recipients', models.ManyToManyField(to='core.Contact')),
                ('smtp_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SMTPSetting')),
            ],
            options={
                'verbose_name_plural': 'Standard Messaging',
            },
        ),
    ]
