# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160812_0233'),
        ('messaging', '0002_queuedmessages_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_value', models.PositiveSmallIntegerField()),
                ('delta_type', models.CharField(choices=[('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks'), ('month', 'Months'), ('year', 'Years')], default='day', max_length=20)),
                ('delta_direction', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderMessaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_column', models.CharField(max_length=500)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('running', 'running'), ('completed', 'completed')], default='draft', max_length=100, no_check_for_status=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact_group', models.ManyToManyField(to='core.ContactGroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
                ('custom_data_namespace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CustomData')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MessageTemplate')),
            ],
            options={
                'verbose_name_plural': 'Reminder Messaging',
            },
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.ReminderMessaging'),
        ),
    ]
