# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20160812_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindermessaging',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
