# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20160813_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningmessage',
            old_name='job',
            new_name='sent_details',
        ),
        migrations.RenameField(
            model_name='runningmessage',
            old_name='first_run_at',
            new_name='started_at',
        ),
    ]
