# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kituser_free_sms_balance'),
        ('messaging', '0007_auto_20160815_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to='issue_feedback/')),
                ('resolution_flag', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailreport',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='smsreport',
            name='owner',
        ),
        migrations.DeleteModel(
            name='EmailReport',
        ),
        migrations.DeleteModel(
            name='SMSReport',
        ),
    ]
