# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 19:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160823_2012'),
        ('messaging', '0008_auto_20160823_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('reason', models.CharField(max_length=255)),
                ('retries', models.PositiveSmallIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
        migrations.CreateModel(
            name='FailedSMSMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('reason', models.CharField(max_length=255)),
                ('retries', models.PositiveSmallIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
    ]
