# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kitubalance'),
        ('messaging', '0009_failedemailmessage_failedsmsmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedMessages',
        ),
        migrations.CreateModel(
            name='ProcessedMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('ADVANCED', ' Advanced'), ('STANDARD', ' Standard'), ('REMINDER', ' Reminder')], max_length=10)),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
            options={
                'verbose_name_plural': 'Processed Messages',
            },
        ),
    ]
