# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 11:56
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20160825_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedemailmessage',
            name='email_pickled_data',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedsmsmessage',
            name='sms_pickled_data',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
            preserve_default=False,
        ),
    ]
