# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160905_0115'),
        ('messaging', '0011_auto_20160905_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedKITMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_data', picklefield.fields.PickledObjectField(editable=False)),
                ('message_category', models.CharField(choices=[('running_msg', 'Running'), ('queued_msg', 'Queued'), ('private_anniv_msg', 'Private Anniv.'), ('public_anniv_msg', 'Public Anniv.')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
        migrations.AlterField(
            model_name='failedemailmessage',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='failedsmsmessage',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
