# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_auto_20160905_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedemailmessage',
            name='email_message',
        ),
        migrations.RemoveField(
            model_name='failedsmsmessage',
            name='sms_message',
        ),
    ]
