# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160908_1035'),
        ('messaging', '0014_auto_20160908_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedSMSSystemBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_pickled_data', picklefield.fields.PickledObjectField(editable=False)),
                ('reason', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
    ]
