# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_failedsmssystembacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardmessaging',
            name='insert_optout',
            field=models.BooleanField(default=1, verbose_name='Insert Unsubscribe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardmessaging',
            name='sms_sender',
            field=models.CharField(blank=True, max_length=11, verbose_name='SMS Sender'),
        ),
    ]
