# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_auto_20160918_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedsmsmessage',
            name='batch_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='failedsmssystembacklog',
            name='batch_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='standardmessaging',
            name='smtp_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SMTPSetting', verbose_name='SMTP Account'),
        ),
    ]
