# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20160921_2123'),
        ('messaging', '0017_auto_20160919_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedmessaging',
            name='custom_data_namespace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.CustomData'),
        ),
    ]
