# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_auto_20160926_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedmessaging',
            name='repeat_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
