# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0023_auto_20160927_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmessaging',
            name='copied_recipients',
            field=models.ManyToManyField(blank=True, help_text='Contacts selected in this field will receive a copy of the messages sent to Recipients', related_name='cc_recipients', to='core.Contact'),
        ),
    ]
