# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0024_auto_20160927_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failedkitmessage',
            options={'verbose_name': 'Failed Message'},
        ),
    ]
