# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to='issue_feedback/')),
                ('resolution_flag', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.KITUser')),
            ],
        ),
        migrations.CreateModel(
            name='KITBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField()),
                ('registered_on', models.DateField()),
                ('billing_cycle', models.CharField(choices=[('QU', 'Quarterly'), ('AN', 'Annually')], default='AN', max_length=2)),
                ('account_status', models.CharField(choices=[('PE', 'Pending'), ('AC', 'Active'), ('SU', 'Suspended'), ('TE', 'Terminated'), ('CA', 'Cancelled'), ('FR', 'Fraud')], default='PE', max_length=2)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kit_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.KITUser')),
            ],
            options={
                'verbose_name': 'Billing',
            },
        ),
        migrations.CreateModel(
            name='KITServicePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KITSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_wide_contacts', models.BooleanField(help_text='Check if you want all users to see contacts from all groups', verbose_name='Organisation-wide Contacts')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('kit_admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.KITUser')),
            ],
        ),
        migrations.AddField(
            model_name='kitbilling',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gomez.KITServicePlan'),
        ),
    ]
