# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdata',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CustomData',
        ),
    ]
