# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitbilling',
            name='next_due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kitbilling',
            name='registered_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kitbilling',
            name='service_plan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gomez.KITServicePlan'),
        ),
        migrations.AlterField(
            model_name='kitsystem',
            name='company_wide_contacts',
            field=models.BooleanField(default=True, help_text='Check if you want all users to see contacts from all groups', verbose_name='Organisation-wide Contacts'),
        ),
    ]
