# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0002_auto_20160729_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitbilling',
            name='service_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gomez.KITServicePlan'),
        ),
    ]
