# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0002_auto_20160812_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitserviceplan',
            name='ad_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='can_use_custom_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='free_sms',
            field=models.BooleanField(default=False, help_text='Weekly Free SMS?'),
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='free_sms_units',
            field=models.PositiveIntegerField(default=0, help_text='Number of Weekly Free SMS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='sms_unit_bundle',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='user_accounts_allowed',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='user_groups_allowed',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
