# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0003_auto_20160729_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitbilling',
            name='next_due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kitbilling',
            name='registered_on',
            field=models.DateField(),
        ),
    ]
