# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0003_auto_20160818_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitbilling',
            name='is_full_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kitserviceplan',
            name='free_sms_units',
            field=models.PositiveIntegerField(default=0, help_text='Number of Weekly Free SMS'),
        ),
        migrations.AlterField(
            model_name='kitserviceplan',
            name='sms_unit_bundle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kitserviceplan',
            name='user_accounts_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kitserviceplan',
            name='user_groups_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
