# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0004_auto_20160818_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_units', models.PositiveIntegerField(default=0)),
                ('dialcode', models.ForeignKey(help_text='Select Prefix', on_delete=django.db.models.deletion.CASCADE, to='country_dialcode.Prefix', verbose_name='Destination')),
            ],
        ),
    ]
