# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kituser_free_sms_balance'),
        ('gomez', '0005_smsratetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[(0, 'Sent'), (1, 'Delivered'), (2, 'Deferred'), (3, 'Bounce')], default=0, max_length=100, no_check_for_status=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('email_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('email_gateway', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
        ),
        migrations.CreateModel(
            name='SMSReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('sms_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sms_gateway', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', model_utils.fields.StatusField(choices=[(0, 'Delivered'), (1, 'Accepted'), (2, 'Expired'), (3, 'Undelivered'), (4, 'Rejected')], default=0, max_length=100, no_check_for_status=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.KITUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='issuefeedback',
            name='submitter',
        ),
        migrations.DeleteModel(
            name='IssueFeedback',
        ),
    ]
