# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0007_kitubalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitubalance',
            name='kit_user',
        ),
        migrations.DeleteModel(
            name='KITUBalance',
        ),
    ]
