# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0009_smsreport_gw_msg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incal',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='kitbilling',
            name='is_full_admin',
        ),
        migrations.RemoveField(
            model_name='kitserviceplan',
            name='ad_supported',
        ),
        migrations.AddField(
            model_name='kitserviceplan',
            name='data_collection_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='InCal',
        ),
    ]
