# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 00:15
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0010_auto_20160903_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreport',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='sent', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='delivered', max_length=100, no_check_for_status=True),
        ),
    ]
