# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0011_auto_20160905_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsratetable',
            name='dialcode',
            field=models.OneToOneField(help_text='Select Prefix', on_delete=django.db.models.deletion.CASCADE, to='country_dialcode.Prefix', verbose_name='Destination'),
        ),
    ]
