# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0013_kitsystem_sms_unsubscribe_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitsystem',
            name='sms_unsubscribe_message',
            field=models.TextField(default='To Stop receiving SMS from us, click', help_text='We will automatically insert the opt-out link at the end                                               of this message', max_length='300', verbose_name='SMS Opt-out Message'),
        ),
    ]
