# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0014_auto_20160919_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitsystem',
            name='default_sms_sender',
            field=models.CharField(blank=True, help_text='Set a Default SMS Sender that will be Pre-filled where necessary', max_length=11, verbose_name='Default SMS Sender'),
        ),
    ]
