# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 17:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import livefield.fields
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_smtpsetting_cloud_smtp_configuration'),
        ('gomez', '0016_auto_20161007_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gateway_detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gateway_type', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('BANK', 'Bank')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='paytype',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.KITUser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_raised',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_alt',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gomez.Order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPA', 'Unpaid'), ('OVDU', 'Overdue'), ('CAND', 'Cancelled'), ('REFD', 'Refunded')], default='UNPA', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_net',
            field=django_prices.models.PriceField(blank=True, currency='NGN', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=django_prices.models.PriceField(blank=True, currency='NGN', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='live',
            field=livefield.fields.LiveField(default=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='billing_cycle',
            field=models.CharField(choices=[('OT', 'One Time'), ('MO', 'Monthly - 1month'), ('QU', 'Quarterly - 3months'), ('BI', 'Biannually - 6months'), ('AN', 'Annually - 1year'), ('BE', 'Biennially - 2years')], default='AN', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitbilling',
            name='billing_cycle',
            field=models.CharField(choices=[('MO', 'Monthly'), ('QU', 'Quarterly'), ('BI', 'Semi-Annually'), ('AN', 'Annually'), ('BE', 'Biennially')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, exclude_lower=True, exclude_vowels=True, length=10, max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gomez.PaymentMethod'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('id', 'order_number', 'live')]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gomez.PaymentMethod'),
        ),
    ]
