# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-10 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0018_auto_20161010_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gomez.PaymentMethod'),
        ),
    ]
