# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0019_auto_20161010_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='unit_price_gross',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Gross Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price_net',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Net Price'),
            preserve_default=False,
        ),
    ]
