# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0020_auto_20161023_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitsystem',
            name='did_number',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='DID Number'),
        ),
        migrations.AddField(
            model_name='kitsystem',
            name='user_phone_as_callerid',
            field=models.BooleanField(default=False),
        ),
    ]
