# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_dialcode', '0001_initial'),
        ('gomez', '0021_auto_20161108_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dialcode', models.OneToOneField(help_text='Select Prefix', on_delete=django.db.models.deletion.CASCADE, to='country_dialcode.Prefix', verbose_name='Destination')),
            ],
        ),
        migrations.RemoveField(
            model_name='smsratetable',
            name='sms_units',
        ),
        migrations.AddField(
            model_name='smsratetable',
            name='sms_cost',
            field=models.DecimalField(decimal_places=4, default=1.8, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitsystem',
            name='did_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='DID Number'),
        ),
        migrations.AlterField(
            model_name='kitsystem',
            name='user_phone_as_callerid',
            field=models.BooleanField(default=False, verbose_name='User Phone Number as Caller ID'),
        ),
    ]
