# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0022_auto_20161108_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitsystem',
            name='max_standard_message',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of Recipients Allowed for Standard Message'),
        ),
    ]
