# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-18 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomez', '0024_remove_kitsystem_user_phone_as_callerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitsystem',
            name='default_message_send_time',
            field=models.TimeField(default=datetime.time(7, 46), verbose_name='Default Message Send Time'),
        ),
    ]
