# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0003_auto_20160914_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='batch_id',
            field=models.UUIDField(db_index=True, editable=False, help_text='A.K.A Process ID or Bulk ID', null=True),
        ),
    ]
