# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0004_auto_20160914_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdeliveryreport',
            name='kituser_parent_id',
            field=models.IntegerField(db_index=True, default=32),
            preserve_default=False,
        ),
    ]
