# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0006_auto_20160914_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='msg_error',
            field=models.CharField(choices=[('0', 'OK'), ('1', 'HANDSET_ERROR'), ('2', 'USER_ERROR'), ('3', 'OPERATOR_ERROR')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='msg_status',
            field=models.CharField(choices=[('0', 'ACCEPTED'), ('1', 'PENDING'), ('2', 'UNDELIVERABLE'), ('3', 'DELIVERED'), ('4', 'EXPIRED'), ('5', 'REJECTED')], default='', max_length=20),
        ),
    ]
