# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0009_calldetailreporttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetailreporttransaction',
            name='call_uuid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
