# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0010_calldetailreporttransaction_call_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailReport',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('a_leg_billsec', models.PositiveIntegerField(default=0)),
                ('b_leg_billsec', models.PositiveIntegerField(blank=True, default=0)),
                ('a_leg_callerid', models.CharField(max_length=50)),
                ('b_leg_callerid', models.CharField(blank=True, max_length=50)),
                ('a_leg_called_number', models.CharField(max_length=50)),
                ('b_leg_called_number', models.CharField(blank=True, max_length=50)),
                ('a_leg_call_start', models.DateTimeField()),
                ('total_call_duration', models.PositiveIntegerField(default=0, help_text='Call duration in seconds')),
                ('per_min_call_price', django_prices.models.PriceField(currency='NGN', decimal_places=2, max_digits=12, verbose_name='Price')),
                ('kituser_id', models.IntegerField(db_index=True)),
                ('kitu_parent_id', models.IntegerField(db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('a_leg_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acdrt', to='reportng.CallDetailReportTransaction')),
                ('b_leg_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcdrt', to='reportng.CallDetailReportTransaction')),
            ],
        ),
    ]
