# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0011_calldetailreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calldetailreport',
            old_name='per_min_call_price',
            new_name='a_leg_per_min_call_price',
        ),
        migrations.RemoveField(
            model_name='calldetailreport',
            name='total_call_duration',
        ),
        migrations.AddField(
            model_name='calldetailreport',
            name='b_leg_per_min_call_price',
            field=django_prices.models.PriceField(currency='NGN', decimal_places=2, default=0, max_digits=12, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calldetailreport',
            name='total_call_cost',
            field=django_prices.models.PriceField(currency='NGN', decimal_places=2, default=0, max_digits=12, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldetailreport',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calldetailreport',
            name='kitu_parent_id',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='calldetailreport',
            name='kituser_id',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emaildeliveryreport',
            name='kitu_parent_id',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emaildeliveryreport',
            name='kituser_id',
            field=models.IntegerField(db_index=True, editable=False),
        ),
    ]
