# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0012_auto_20161109_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailreport',
            name='a_leg_call_start',
            field=models.DateTimeField(null=True),
        ),
    ]
