# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0015_auto_20161110_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailreport',
            name='a_leg_billsec',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='calldetailreport',
            name='b_leg_billsec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12),
        ),
    ]
