# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 09:52
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0018_auto_20161110_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailreport',
            name='a_leg_per_min_call_price',
            field=django_prices.models.PriceField(currency='NGN', decimal_places=2, default=0, max_digits=12, verbose_name='A-Leg Cost'),
        ),
        migrations.AlterField(
            model_name='calldetailreport',
            name='b_leg_per_min_call_price',
            field=django_prices.models.PriceField(currency='NGN', decimal_places=2, default=0, max_digits=12, verbose_name='B-Leg Cost'),
        ),
        migrations.AlterField(
            model_name='calldetailreport',
            name='total_call_cost',
            field=django_prices.models.PriceField(currency='NGN', decimal_places=2, max_digits=12, null=True, verbose_name='Total Cost'),
        ),
    ]
