# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    
    #('reportng', '0020_auto_20161110_2147'),
    dependencies = [
        ('reportng', '0019_auto_20161110_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetailreport',
            name='a_leg_uuid',
        ),
        migrations.RemoveField(
            model_name='calldetailreport',
            name='b_leg_uuid',
        ),
    ]
