# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0020_auto_20161110_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetailreporttransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='calldetailreporttransaction',
            name='call_uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
