# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0021_auto_20161110_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetailreport',
            name='a_leg_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acdrt', to='reportng.CallDetailReportTransaction'),
        ),
        migrations.AddField(
            model_name='calldetailreport',
            name='b_leg_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcdrt', to='reportng.CallDetailReportTransaction'),
        ),
    ]
