# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 16:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0022_auto_20161110_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReportTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('0', 'Unprocessed'), ('1', 'Processed'), ('2', 'Error')], default='0', max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='emaileventhistory',
            old_name='data',
            new_name='evdata',
        ),
        migrations.AddField(
            model_name='emaileventhistory',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emaileventhistory',
            name='evtype',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='emaildeliveryreport',
            name='msg_status',
            field=models.CharField(choices=[('0', 'SENT'), ('1', 'PROCESSED'), ('2', 'DROPPED'), ('3', 'DEFERRED'), ('4', 'DELIVERED'), ('5', 'BOUNCED'), ('6', 'SENDING...')], default='', max_length=20),
        ),
    ]
