# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-04 20:23
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reportng', '0023_auto_20161202_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReceiverAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('1', 'OPENED'), ('2', 'CLICKED'), ('7', 'SPAM REPORT')], max_length=2)),
                ('action_time', models.DateTimeField()),
                ('note', models.TextField()),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emaildeliveryreport',
            old_name='created',
            new_name='processed',
        ),
        migrations.AddField(
            model_name='emaildeliveryreport',
            name='sent_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 20, 23, 59, 398811, tzinfo=utc), verbose_name='Sent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailreceiveraction',
            name='email_delivery_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportng.EmailDeliveryReport'),
        ),
    ]
